In [1]:
import torch

In [2]:
# Construct a 5x3 matrix,uninitialized
x = torch.empty(5, 3)
print(x)

tensor([[5.1429e-39, 4.2246e-39, 1.0286e-38],
        [1.0653e-38, 1.0194e-38, 8.4490e-39],
        [1.0469e-38, 9.3674e-39, 9.9184e-39],
        [8.7245e-39, 9.2755e-39, 8.9082e-39],
        [9.9184e-39, 8.4490e-39, 9.6429e-39]])


In [3]:
# Construct a randomly initialized matrix
x = torch.rand(5, 3)
print(x)

tensor([[0.0215, 0.9107, 0.9714],
        [0.9785, 0.4207, 0.8198],
        [0.3898, 0.5895, 0.7870],
        [0.9981, 0.3753, 0.3596],
        [0.2431, 0.2752, 0.6794]])


In [5]:
# Construct a tensor filled with random numbers from a normal distribution
# with mean `0` and variance `1` (also called the standard normal
# distribution).
x = torch.randn(5, 3)
print(x)

tensor([[-1.0093, -0.3426,  1.2647],
        [-0.4868, -0.4671,  0.6136],
        [ 1.0208, -0.3877, -0.4818],
        [ 0.8627, -1.4403, -1.0268],
        [ 0.3501,  0.2876, -1.2152]])


In [6]:
# Construct a matrix filled zeros and of dtype long:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [10]:
x.new_ones((5, 3)).dtype   # new_ones()方法重用了输入Tensor的属性， 可以自己更改属性

torch.int64

In [12]:
torch.randn_like(x, dtype=torch.float)  # 返回与x同样size的tensor

tensor([[ 0.2416,  0.2961,  1.0952],
        [ 1.0327,  1.1137,  1.8395],
        [ 0.7829,  0.4558,  0.9509],
        [-0.1997, -1.4928, -0.1038],
        [-2.3870,  1.0078,  0.6317]])

`torch.size`实际为一个元组，支持所有元组的操作

In [16]:
x.size()[0], x.size()[1]

(5, 3)

Tensor的一些操作

In [17]:
# tensor的几种add element-wise操作
y = torch.rand(5, 3)
print(x + y)

print(torch.add(x, y))

result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[0.5788, 0.2184, 0.7907],
        [0.3803, 0.0891, 0.4541],
        [0.7414, 0.2214, 0.3084],
        [0.0484, 0.8711, 0.6190],
        [0.9230, 0.9753, 0.1508]])
tensor([[0.5788, 0.2184, 0.7907],
        [0.3803, 0.0891, 0.4541],
        [0.7414, 0.2214, 0.3084],
        [0.0484, 0.8711, 0.6190],
        [0.9230, 0.9753, 0.1508]])
tensor([[0.5788, 0.2184, 0.7907],
        [0.3803, 0.0891, 0.4541],
        [0.7414, 0.2214, 0.3084],
        [0.0484, 0.8711, 0.6190],
        [0.9230, 0.9753, 0.1508]])


In [19]:
print(x)
print(y)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([[0.5788, 0.2184, 0.7907],
        [0.3803, 0.0891, 0.4541],
        [0.7414, 0.2214, 0.3084],
        [0.0484, 0.8711, 0.6190],
        [0.9230, 0.9753, 0.1508]])


In [21]:
x = torch.randn(5, 3)
print(x)

tensor([[ 1.2527, -0.7031, -2.2256],
        [ 0.7419,  2.2049,  0.1413],
        [ 0.7078,  0.8888, -0.7644],
        [-1.1713, -2.4900, -0.9809],
        [-0.9715,  0.3010, -2.7172]])


In [22]:
y.add(x)
print(y)
y.add_(x)
print(y)

tensor([[0.5788, 0.2184, 0.7907],
        [0.3803, 0.0891, 0.4541],
        [0.7414, 0.2214, 0.3084],
        [0.0484, 0.8711, 0.6190],
        [0.9230, 0.9753, 0.1508]])
tensor([[ 1.8315, -0.4847, -1.4349],
        [ 1.1222,  2.2940,  0.5954],
        [ 1.4492,  1.1102, -0.4560],
        [-1.1229, -1.6188, -0.3619],
        [-0.0485,  1.2762, -2.5664]])


重整tensor的形状  
use `torch.view`

In [24]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)   # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


对于仅有一个元素的tensor，使用`.item()`得到该元素的值(as a Python number)

In [27]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.3651])
-0.365104079246521


# Numpy形式与Tensor形式的转换
Tensor和NumPy数组将共享它们的底层内存位置(CPU)，改变其中一个就会改变另一个。

In [28]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [29]:
# Tensor ---> Numpy
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [30]:
a.add_(1)
print(a)
print(b)    # a与b共享内存

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [31]:
# Numpy ---> Tensor
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# cuda版本尚未安装