In [1]:
import numpy as np

In [3]:
a = np.array([[1,2],[3,4]])
b = np.array([[1,2],[3,4]])

In [4]:
a.shape,b.shape

((2, 2), (2, 2))

In [5]:
np.multiply(a, b)

array([[ 1,  4],
       [ 9, 16]])

In [6]:
a * b

array([[ 1,  4],
       [ 9, 16]])

In [7]:
a @ b

array([[ 7, 10],
       [15, 22]])

In [8]:
a = np.matrix(a)
b = np.matrix(b)
a.shape,b.shape

((2, 2), (2, 2))

In [9]:
a * b

matrix([[ 7, 10],
        [15, 22]])

In [10]:
np.multiply(a, b)

matrix([[ 1,  4],
        [ 9, 16]])

In [11]:
a @ b

matrix([[ 7, 10],
        [15, 22]])

# 查看multiply()、*、@d的区别