# 1.Numpy ndarry(多维数组对象)

In [1]:
import numpy as np

np.arange()

In [2]:
np.arange(10)      # 类似于python中的range()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

创建array的几种方式

In [3]:
arr = np.zeros((4, 4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
arr = np.empty((4, 2))
arr

array([[0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 6.04736351e-321],
       [1.33511561e-306, 9.34605715e-307]])

In [5]:
arr = np.random.randn(4, 5)   # 随机生成数据
arr

array([[ 0.56252934, -1.03963054,  0.35523732,  0.36562826,  0.19587349],
       [-2.25268617, -0.06864326,  1.6660145 , -0.08880352, -0.33595325],
       [-0.3352674 , -0.94923966, -0.72572044, -1.24442244,  1.04543474],
       [-0.33156411, -1.24683638,  0.91460502, -1.95905057,  0.27595382]])

In [6]:
# 指定数据
data = [[1, 2, 3],[4, 5, 6]]
arr = np.array(data)
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
arr.shape

(2, 3)

布尔索引

In [12]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [10]:
data = np.random.randn(7, 4)
data

array([[-0.64109111, -1.2155192 , -0.36753319,  0.10450178],
       [-0.44873218,  0.30437061,  0.44378163,  0.12899722],
       [-0.83628148, -0.17915039, -0.10893685, -0.04529575],
       [ 0.69959343, -0.70379136, -1.15460156, -0.0586076 ],
       [ 0.37274409,  0.34874932,  1.34711101, -0.87860672],
       [-0.38457896, -1.32483429, -0.0891612 , -0.88543564],
       [ 0.09376728, -0.09943039,  0.0419907 ,  0.79024765]])

In [13]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [14]:
# 使用布尔数组作为索引
data[names == 'Bob']   # 选中值为True的索引

array([[-0.64109111, -1.2155192 , -0.36753319,  0.10450178],
       [ 0.69959343, -0.70379136, -1.15460156, -0.0586076 ]])

需要注意的是，使用布尔索引会返回一份新创建的数据，原本数据不会改变

In [15]:
data[names == 'Bob'] = 0
data

array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [-0.44873218,  0.30437061,  0.44378163,  0.12899722],
       [-0.83628148, -0.17915039, -0.10893685, -0.04529575],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.37274409,  0.34874932,  1.34711101, -0.87860672],
       [-0.38457896, -1.32483429, -0.0891612 , -0.88543564],
       [ 0.09376728, -0.09943039,  0.0419907 ,  0.79024765]])

# 2.通用函数（快速点对点数组函数）

In [16]:
import numpy as np
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [18]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [19]:
x = np.random.randn(8)
y = np.random.randn(8)
print(x, y)

[-0.77893841  1.57568733 -0.80151264  0.47705658  0.30372863  1.04001381
  0.16191646  0.83830532] [-0.20068694 -2.22729069 -1.37855322 -0.95423081  1.8593704  -0.13212937
 -0.31678846  1.28287585]


In [20]:
np.maximum(x, y)

array([-0.20068694,  1.57568733, -0.80151264,  0.47705658,  1.8593704 ,
        1.04001381,  0.16191646,  1.28287585])

逐项元素分别比较

# 3.np.where()

In [22]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

将array中大于0的数变为2，小于0的数变为-2

In [23]:
arr = np.random.randn(4, 4)
arr

array([[-0.6082505 ,  2.21703166, -0.89503873,  0.47148907],
       [ 0.80778849, -1.82533016,  0.64759618, -0.2269156 ],
       [-1.29740198,  0.55272719, -0.02499187,  0.64316609],
       [ 0.08960776, -1.34275266,  0.36606577,  2.421463  ]])

In [24]:
arr > 0

array([[False,  True, False,  True],
       [ True, False,  True, False],
       [False,  True, False,  True],
       [ True, False,  True,  True]])

In [25]:
np.where(arr > 0, 2, -2)

array([[-2,  2, -2,  2],
       [ 2, -2,  2, -2],
       [-2,  2, -2,  2],
       [ 2, -2,  2,  2]])

# 4.数学和统计方法

In [26]:
arr = np.random.randn(5, 4)
arr

array([[-1.23270444,  0.25543005, -0.85542975, -0.62378113],
       [ 1.46091741,  0.55487165,  0.6172556 ,  0.34722609],
       [-0.18850001, -0.386278  ,  0.72270309, -0.87523586],
       [-0.31802126, -0.26673613,  0.2909095 ,  0.10727421],
       [-0.04377858, -0.05906707, -0.38406195,  0.60924746]])

In [27]:
arr.mean()

-0.013387956233930043

In [28]:
arr.sum()

-0.26775912467860086

也可以指定axis进行计算

In [29]:
arr.mean(axis=1)

array([-0.61412132,  0.74506769, -0.1818277 , -0.04664342,  0.03058496])

In [30]:
arr.sum(axis=0)

array([-0.32208688,  0.0982205 ,  0.39137649, -0.43526923])

axis=1是对列进行操作，axis=0是对行进行操作

In [31]:
# any()和all()方法
bools = np.array([False, False, True, False])

In [32]:
bools.any()  # 数组中只要有一个True就返回True

True

In [34]:
bools.all()

False

In [35]:
# 返回排好序且不重复的值
np.unique?

# 5.文件的输入和输出
Numpy能从磁盘直接存储和加载数据，无论是文本格式还是二进制模式。  
np.save和np.load。 数组以未压缩的原始二进制模式保存，后缀为.npy

In [41]:
import numpy as np

arr = np.arange(10)
np.save('arr', arr)  # 保存

In [42]:
np.load('arr.npy')  # 加载

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
a = np.array([[1, 2, 3],[4, 5, 6]])
b = np.arange(0, 1.0, 0.1)
c = np.sin(b)

In [44]:
# np.savez()保存多个数组，字典形式
np.savez('result.npz', a, b, sin_arr=c)

In [45]:
np.load('result.npz')['sin_arr']

array([0.        , 0.09983342, 0.19866933, 0.29552021, 0.38941834,
       0.47942554, 0.56464247, 0.64421769, 0.71735609, 0.78332691])

# 6.Numpy数组的合并
常用np.concatenate()，可以指定纵向or横向合并

In [1]:
import numpy as np

a = np.array([1, 1, 1])
b = np.array([2, 2, 2])

In [2]:
c = np.concatenate((a, b), axis=1)
c

AxisError: axis 1 is out of bounds for array of dimension 1

注意一下维度

In [3]:
print(a.shape)
print(a[np.newaxis,:])  # 增加一个维度

(3,)
[[1 1 1]]


In [4]:
a = a[np.newaxis,:]
b = b[np.newaxis,:]
a, b

(array([[1, 1, 1]]), array([[2, 2, 2]]))

In [5]:
c = np.concatenate((a, b), axis=1)
c

array([[1, 1, 1, 2, 2, 2]])

In [6]:
c = np.concatenate((a, b), axis=0)
c

array([[1, 1, 1],
       [2, 2, 2]])

# 7.Numpy数组的分割

In [7]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
np.split(a, 2, axis=1)  # 指定纵向分割,仅能均匀分割

[array([[0, 1],
        [4, 5],
        [8, 9]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [9]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
np.array_split(a, 3, axis=1)  # 不均匀分割

[array([[0, 1],
        [4, 5],
        [8, 9]]), array([[ 2],
        [ 6],
        [10]]), array([[ 3],
        [ 7],
        [11]])]

In [12]:
print(np.vsplit(a, 3))
print(np.hsplit(a, 2))

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


# 8.Numpy的copy() & deep copy

In [13]:
a = np.array([1, 2, 3, 4])
b = a
c = b

In [14]:
a, b, c

(array([1, 2, 3, 4]), array([1, 2, 3, 4]), array([1, 2, 3, 4]))

In [15]:
a[0] = 11
a

array([11,  2,  3,  4])

In [16]:
print(b is a)
print(c is a)

True
True


In [17]:
a, b, c

(array([11,  2,  3,  4]), array([11,  2,  3,  4]), array([11,  2,  3,  4]))

我们会发现a,b,c指向了同一存储区域,为了切断它们之间的关联，可以使用copy()函数

In [18]:
b = a.copy()
print(b is a)

False


In [20]:
b[:2] = 0
a, b

(array([11,  2,  3,  4]), array([0, 0, 3, 4]))